### ISSUE TITLE
Plugin error (bad file descriptor)

### ISSUE THREAD

**Issue by BT3D** [nejcd/LidarSloveniaDataDownloader#7]
Traceback (most recent call last):
			  File "C:/Users/xxx/.qgis2/python/plugins\LidarSloveniaDataDownloader\LidarSloveniaDataDownloader.py", line 354, in download
			    downloaded = self.downloadLSS(url, filename, destination, n, ntiles)
			  File "C:/Users/xxx/.qgis2/python/plugins\LidarSloveniaDataDownloader\LidarSloveniaDataDownloader.py", line 324, in downloadLSS
			    print done
			IOError: [Errno 9] Bad file descriptor

**Comment by pbrgle1** [comment]
I have the same problem. Is there a solution? I'm using QGIS 2.18.25
Would be very grateful if there was a fix.
